
import numpy as np
from scipy.linalg import expm
from Structs import Param
from scipy.optimize import linear_sum_assignment
from fiboancci_funcs import *

def skew(x):
    """
    Obtain skew-symmetric matrix from vector.

    Supports:
      - n = 3: so(3)
      - n = 1: so(2)

    Parameters
    ----------
    x : array-like
        Input vector.

    Returns
    -------
    X : ndarray
        Skew-symmetric matrix.
    """
    x = np.asarray(x).flatten()
    n = len(x)

    if n == 3:
        X = np.array([
            [0,    -x[2],  x[1]],
            [x[2],  0,   -x[0]],
            [-x[1], x[0], 0]
        ])

    elif n == 1:
        X = np.array([
            [0,    -x[0]],
            [x[0],  0]
        ])

    else:
        raise ValueError(
            "SKEW function not implemented for input dimensions other than "
            "1 or 3 (i.e., so(2) and so(3))."
        )

    return X

def unskew(M):
    """
    Extracts the vector from a 3x3 skew-symmetric matrix.
    """
    return np.array([
        [M[2, 1]],
        [M[0, 2]],
        [M[1, 0]]
    ])

def rot_integrate(R, om, dT):
    """
    Integrate rotation matrix using angular velocity.
    
    Parameters:
        R : ndarray, shape (3,3)
            Initial rotation matrix
        om : array-like, shape (3,)
            Angular velocity vector
        dT : float
            Time step
            
    Returns:
        Rp : ndarray, shape (3,3)
            Updated rotation matrix
    """
    # om is constant over the step, so the 10 sub-step exponentials collapse
    # into a single one: R @ expm(dT*skew(om)), evaluated in closed form
    # (Rodrigues formula) instead of the generic scipy expm.
    om = np.asarray(om, dtype=float).flatten()
    theta = np.linalg.norm(om) * dT

    if theta < 1e-12:
        return R.copy()

    K = skew(om / np.linalg.norm(om))
    Rot = (
        np.eye(3)
        + np.sin(theta) * K
        + (1 - np.cos(theta)) * (K @ K)
    )

    return R @ Rot

import numpy as np

def Euler2R(ang):
    """
    Converts an Euler angles vector [phi, theta, psi] into a rotation matrix
    of the Z-Y-X representation:
        R = rot_z(psi) * rot_y(theta) * rot_x(phi)

    Parameters:
        ang : array-like
            Euler angles [phi, theta, psi] in radians

    Returns:
        rot : numpy.ndarray
            3x3 rotation matrix
    """

    phi, theta, psi = ang

    rotx = np.array([
        [1, 0, 0],
        [0, np.cos(phi), -np.sin(phi)],
        [0, np.sin(phi),  np.cos(phi)]
    ])

    roty = np.array([
        [ np.cos(theta), 0, np.sin(theta)],
        [0,              1, 0],
        [-np.sin(theta), 0, np.cos(theta)]
    ])

    rotz = np.array([
        [np.cos(psi), -np.sin(psi), 0],
        [np.sin(psi),  np.cos(psi), 0],
        [0,            0,           1]
    ])

    rot = rotz @ roty @ rotx

    return rot

def linear_motion_ref(q, q_d, param: Param):
    """
    Linear motion reference update.

    Parameters
    ----------
    q : ndarray, shape (3,)
        Current reduced attitude vector.
    q_d : ndarray, shape (3,)
        Desired reduced attitude vector.
    param : object
        Object with attributes:
            - k_geometric : float
            - dTi : float

    Returns
    -------
    q : ndarray, shape (3,)
        Updated reduced attitude.
    e_q : ndarray, shape (3,)
        Configuration error.
    """
    # ---------- Configuration error ----------
    e_q = skew(q_d) @ q / np.sqrt(2 * (1 + np.dot(q.T, q_d)))

    # ---------- Reduced attitude kinematics ----------
    q_dot = -param.k_geometric * (skew(e_q) @ q)
    q = q + param.sim.dTi * q_dot
    q = q / np.linalg.norm(q)

    return q, e_q

import numpy as np


def apf_safe_guard(iD, q_ref, q_positions, min_safe_dist, param: Param, geo_matrix=None):
    """
    Artificial Potential Field (APF) collision avoidance.

    Applies the repulsive tangential displacement to the reference direction
    q_ref generated by the geometric controller, i.e. d_i = PI(q_ref + f_total).

    Parameters
    ----------
    iD : int
        Index of the current drone (0-based indexing).
    q_ref : ndarray, shape (3, 1)
        Reference reduced attitude vector from the geometric controller.
    q_positions : list of ndarray, shape (3, 1)
        Reduced attitude vectors for all drones.
    min_safe_dist : float
        Minimum allowable geodesic distance.
    param : object
        Object with attributes:
            - nD : int
            - k_apf : float
    geo_matrix : ndarray, shape (nD, nD), optional
        Precomputed pairwise geodesic distances (avoids recomputing the
        full matrix once per drone within the same time step).

    Returns
    -------
    q : ndarray, shape (3, 1)
        Safe reference vector (unit norm).
    """
    # Compute geodesic distances between all pairs
    if geo_matrix is None:
        current_geo_distances = geo_distances(
            np.hstack(q_positions), 1, np.zeros([3, 1])
        )
    else:
        current_geo_distances = geo_matrix

    distances = current_geo_distances[iD, :]
    sorted_idx = np.argsort(distances)
    dist_vals = distances[sorted_idx]

    artificial_potential_vector = np.zeros([3,1])

    # Skip the first entry (distance to itself = 0)
    for i in range(1, param.sim.nD):
        if dist_vals[i] > min_safe_dist or dist_vals[i] == 0:
            continue

        A_point = q_positions[iD]
        B_point = q_positions[sorted_idx[i]]

        # Radial direction
        nA = A_point / np.linalg.norm(A_point)

        # Vector from neighbor to current
        AB = A_point - B_point

        # Remove radial component
        AB_tangent = AB - np.dot(AB.T, nA) * nA

        if np.linalg.norm(AB_tangent) < 1e-6:
            continue

        AB_tangent /= np.linalg.norm(AB_tangent)

        repulsion_mag = (min_safe_dist - dist_vals[i]) * param.k_apf

        artificial_potential_vector += repulsion_mag * AB_tangent

    # Clamp
    norm_apf = np.linalg.norm(artificial_potential_vector)
    if norm_apf > min_safe_dist:
        artificial_potential_vector = (
            artificial_potential_vector / norm_apf * min_safe_dist
        )

    # Apply as displacement to the reference and re-project onto the sphere
    q = q_ref + artificial_potential_vector
    q = q / np.linalg.norm(q)

    return q


def update_radius(Rad, e_q , param: Param):
    # UPDATE_RADIUS Summary of this function goes here
    #   Rad - radius of sphere
    #   e_q - Error value of q position
    #   chaser - chaser drone
    #   target - target drone
    #   Param - Parameters
    # ---------- Radius dynamics (purely scalar) ----------

    # V2 position (from error function)
    Rad_dot = param.k_rad * np.exp(-(np.linalg.norm(e_q) ** 2)) * (param.sim.sphere_radius - Rad)

    Rad += param.sim.dTi * Rad_dot

    return Rad

def assign_agents_to_fibonacci_points(chaser_list, target, fib_ref_points, param):
    """
    Assign each agent to the closest Fibonacci reference point on a sphere
    using the Hungarian algorithm.

    Parameters
    ----------
    chaser_list : list
        List of chaser objects. Each must have:
            - position
            - desired.position
    target : object
        Target object with attribute `position`.
    fib_ref_points : ndarray, shape (nD, 3)
        Fibonacci reference points centered at the origin.
    param : object
        Simulation parameters containing:
            param.sim.nD
            param.sim.sphere_radius

    Returns
    -------
    assignments : ndarray, shape (nD, 2)
        Column 0: reference point index.
        Column 1: assigned agent index.
    assigned_ref : ndarray, shape (nD,)
        assigned_ref[i] gives the reference index assigned to agent i.
    """

    # ------------------------------------------------------------------
    # Collect initial positions
    # ------------------------------------------------------------------
    initial_pos = [chaser.position for chaser in chaser_list]

    pos_on_sphere = project_to_sphere(
        np.hstack(initial_pos),
        param.sim.sphere_radius,
        target.position,
    )

    nD = param.sim.nD
    radius = param.sim.sphere_radius
    center = np.asarray(target.position).reshape(3, 1)

    # ------------------------------------------------------------------
    # Compute geodesic distance matrix
    # ------------------------------------------------------------------
    geo_distances = np.zeros((nD, nD))

    for i in range(nD):
        a = fib_ref_points[i, :]
        for j in range(nD):
            b = pos_on_sphere[:, j:j + 1]

            dot_product = np.dot(a.T, b - center)[0, 0]

            cos_theta = np.clip(
                dot_product / radius**2,
                -1.0,
                1.0,
            )

            geo_distances[i, j] = radius * np.arccos(cos_theta)

    # ------------------------------------------------------------------
    # Hungarian assignment
    # ------------------------------------------------------------------
    row_ind, col_ind = linear_sum_assignment(geo_distances)

    if len(row_ind) != nD:
        raise RuntimeError("ERROR: impossible to assign 1-to-1")

    assignments = np.column_stack((row_ind, col_ind))

    # ------------------------------------------------------------------
    # Assign desired positions
    # ------------------------------------------------------------------
    assigned_ref = np.zeros(nD, dtype=int)

    for ref_idx, agent_idx in assignments:
        assigned_ref[agent_idx] = ref_idx
        chaser_list[agent_idx].desired.position = (
            fib_ref_points[ref_idx, :] + target.position
        )

    return assignments, assigned_ref